### ISSUE TITLE
Publish new minor version?

### ISSUE THREAD

**Issue by MCOfficer** [tokahuke/yaque#24]
An old version of `ntapi` (required by `sysinfo`) is causing build-failures on some systems (see https://github.com/MSxDOS/ntapi/issues/19). 88bbf1833ba466bfe48c298104aec114112858eb already fixes this, so for the time being i can just the master branch.

**Comment by MCOfficer** [comment]
It's already fixed on master, all that's needed is a release.

**Comment by tokahuke** [comment]
Oh! I see. Ok. I will create a new minor.

**Comment by tokahuke** [comment]
v0.6.5 is now live in crates.io
