### ISSUE TITLE
Create a `Peeker<T>` to allow iterating through a queue without consuming the items. 

### ISSUE THREAD

**Issue by tokahuke** [tokahuke/yaque#5]
The `Receiver<T>` consumes the items from the queue (like `.into_iter()`). It Would Be Nice©  to have an equivalent to `.iter()`.

**Comment by vedantroy** [comment]
Hate to be this guy, but is there any update on this?

Another useful alternative would be allowing submission of batches of items, but consuming reads only read 1 item at a time.

**Comment by tokahuke** [comment]
Yes! I have opened this issue a long time ago because I have thought this feature was useful. It looks like it is not. Maybe I will close this issue as irrelevant.

**Comment by tokahuke** [comment]
... except that `recv_batch` and friends **materialize** the peeked result. This may be undesirable in some cases (imagine you want only to count the number of elements in the queue!!).

I think we will need a special API for this, but it can be integrated n the Receiver itself, but I will leave it for a future release (in the "short term"). there is too much already going on in 0.6.0...

**Comment by tokahuke** [comment]
Implemented as QueueIter in PR #12 .
